# Generated by Django 3.1.7 on 2021-03-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_the_game_requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='processor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_card_name',
            field=models.CharField(max_length=100),
        ),
    ]
