# Generated by Django 3.1.7 on 2021-03-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_the_game_requirements', '0003_gametest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video_card_memory',
        ),
        migrations.RemoveField(
            model_name='game',
            name='video_card_name',
        ),
        migrations.AddField(
            model_name='game',
            name='processor_one',
            field=models.ManyToManyField(related_name='processor_one', to='checking_the_game_requirements.Processor'),
        ),
        migrations.AddField(
            model_name='game',
            name='processor_two',
            field=models.ManyToManyField(related_name='processor_two', to='checking_the_game_requirements.Processor'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_card_one',
            field=models.ManyToManyField(related_name='card_one', to='checking_the_game_requirements.VideoCard'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_card_two',
            field=models.ManyToManyField(related_name='card_two', to='checking_the_game_requirements.VideoCard'),
        ),
        migrations.DeleteModel(
            name='GameTest',
        ),
    ]
