# Generated by Django 3.1.7 on 2021-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_the_game_requirements', '0005_processor_benchmarking'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocard',
            name='benchmarking',
            field=models.IntegerField(null=True),
        ),
    ]
