# Generated by Django 3.1.7 on 2021-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_the_game_requirements', '0002_auto_20210324_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('memory', models.IntegerField()),
                ('processor_one', models.ManyToManyField(related_name='processor_one', to='checking_the_game_requirements.Processor')),
                ('processor_two', models.ManyToManyField(related_name='processor_two', to='checking_the_game_requirements.Processor')),
                ('video_card_one', models.ManyToManyField(related_name='card_one', to='checking_the_game_requirements.VideoCard')),
                ('video_card_two', models.ManyToManyField(related_name='card_two', to='checking_the_game_requirements.VideoCard')),
            ],
        ),
    ]
