# Generated by Django 3.1.7 on 2021-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checking_the_game_requirements', '0004_auto_20210327_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='benchmarking',
            field=models.IntegerField(null=True),
        ),
    ]
